[QSTR-116] Adding logic to execute any query that is sent to QStore.
diging/qstore4s pull request #27
Opened 2017-01-23 21:57 UTC by suprajkolluri

Adding logic to execute any query that is sent to QStore and return the result

2017-01-24 19:35 UTC, jdamerow requested changes

2017-01-24 19:35 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +    Converter converter;
where is the access modifier?

2017-01-24 19:35 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +    @RequestMapping(value = "/getResultForQuery", method = RequestMethod.POST)
bad api method name. why not just ```query```?

2017-01-24 19:35 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +    public String getAllNetworks(HttpServletRequest request, HttpServletResponse response,
bad method name

2017-01-24 19:35 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +            response.setStatus(400);
you should use the ```httpstatus``` enum here

2017-01-24 19:35 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +            return "Please provide the query to execute the request";
method should return valid xml/json

2017-01-24 19:35 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +        logger.info("Requested format: " + accept);
why does this need to be logged?

2017-01-24 19:35 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +    private Neo4jOperations template;
do you actually use that object?

2017-01-24 19:35 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/db/neo4j/impl/DbConnector.java
> +        }
this is a bad approach. What if we want to return other objects in the future? This method should take a class object, and then you should validate the input string much earlier and turn it into a class object.

2017-01-24 19:35 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/db/neo4j/impl/DbConnector.java
> +        if ("relationevent".equals(clas.toLowerCase())) {
(almost) never hard-code strings...!

2017-01-25 21:43 UTC, jdamerow requested changes

2017-01-25 21:43 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +            put("appellationevent", AppellationEvent.class);
these strings should be constants.

2017-01-25 21:43 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +            put("appellationevent", AppellationEvent.class);
should also not be static. There is simply no reason here why that would have to be static, and if anything only makes it more difficult to maintain.

2017-01-25 21:43 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +    IRepositoryManager repositorymanager;
access modifier missing

2017-01-25 21:43 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +        if (query.isEmpty()) {
should probably be trimmed

2017-01-25 21:43 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +        edu.asu.qstore4s.error.Error error = null;
initialize where needed

2017-01-25 21:43 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +            return error.toString(accept);
you can probably also merge the two lines into one

2017-01-25 21:43 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +        edu.asu.qstore4s.error.Error error = null;
initialize where needed

2017-01-25 21:43 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +        edu.asu.qstore4s.error.Error error = null;
same here

2017-01-25 21:43 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/domain/events/impl/AppellationEvent.java
> +    Long graphId;
why don't you use the creationEvent graph id?

2017-01-30 16:49 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/controller/QStore.java
> +        Class<?> classs = classMap.get(clas);
typically class objects are called ```clazz```. not a big deal, but ```classs``` looks odd.

2017-01-30 16:51 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/domain/events/impl/CreationEvent.java
> +    @Property(name = "source_reference")
formatting is off

2017-01-30 16:51 UTC, jdamerow commented on QStore4S/src/main/java/edu/asu/qstore4s/domain/events/impl/CreationEvent.java
> +    }
here as well

2017-01-30 16:57 UTC, jdamerow commented
once formatting has been fixed should be ready for merging

2017-01-30 16:57 UTC, jdamerow approved these changes

2017-01-30 17:06 UTC, suprajkolluri commented
@jdamerow Fixed the variable name and formatting

2017-01-30 17:13 UTC, merged